### ISSUE TITLE
关于史低

### ISSUE THREAD

**Issue by EmmettJZK** [ly188128934/steamsd#1]
您好，想问您一下您是怎么实现史低这个功能的，用了什么数据库？

**Comment by somebdly** [comment]
不好意思呢，这个我后来没有继续弄了。这个是个空的项目

**Comment by EmmettJZK** [comment]
好的，因为我最近也对这个比较感兴趣，正在做一个小程序，想实现一个史低的功能，请问您当初做这个是出于什么目的呢。

**Comment by somebdly** [comment]
用于查询steam的价格并列出历史每日超过历史最低价的游戏。不过现在这个好像小黑盒就有这个功能。

**Comment by EmmettJZK** [comment]
> 用于查询steam的价格并列出历史每日超过历史最低价的游戏。不过现在这个好像小黑盒就有这个功能。

我现在也在实现这个，自己做个小程序，有ps4\pc\xbox1\switch 的整合价格  小程序叫极环，正在想怎么实现史低，感兴趣的话可以关注一下哦
